language: php
php:  
  - 8.0
  - 8.1

before_script:
  # Update Composer
  - travis_retry composer self-update

  # Install dependencies
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/tester tests -s -p php -C $NTESTER_FLAGS
  - vendor/modul-is/coding-standard/ecs check src --preset php80
  - vendor/bin/phpstan analyse --level 5 src

after_failure:
  # Print *.actual content
  - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
  directories:
    - $HOME/.composer/cache